# Use this file to store secrets like usernames and passwords.
# Learn more at https: ""
spotcast_spdc: ""
spotcast_spkey: ""
todoist_api_token: ""
todoist_api_token2: ""
todoist_cmd_with_api_token: ""
trusted_proxies: ""