- platform: template
  switches:
    closet_shelly:
      value_template: "{{ is_state('light.closet_light', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.closet_shelly
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.closet_shelly
