
substitutions:
  device_name: ny1-p-workbench-01
  max_power: "800"
  max_temp: "70"

esphome:
  name: $device_name
  friendly_name: NY1-P-WORKBENCH-01


esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "$(device_name) Fallback Hotspot"
    password: !secret fallback_password

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    id: my_ota
    password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO05

# light:
#   - platform: binary
#     name: "Status LED"
#     id: led
#     pin:
#       number: GPIO00
#       inverted: true
status_led:
  pin:
    number: GPIO0
    inverted: yes

switch:
  - platform: output
    id: "relay"
    name: "Power"
    output: "relay_output"
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    mac_address:
        name: ESP Mac Wifi Address
    dns_address:
        name: DNS Address

binary_sensor:
#   - platform: gpio
#     name: "Main Switch"
#     pin: GPIO10
#     on_state: 
#       then:
#         - switch.toggle: "relay"
#     filters:
#       - delayed_on_off: 50ms

  - platform: gpio
    name: "Button"
    pin:
      number: GPIO01
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 5ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Device Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: relay
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${device_name}
              data_template:
                message: Switch turned off because temperature exceeded ${max_temp}°C ({temp_resistance_reading) 
      
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db

  - platform: bl0942
    uart_id: uart_bus
    voltage:
      name: 'Voltage'
    current:
      name: 'Current'
    power:
      name: 'Power'
      id: power
      icon: mdi:flash-outline
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${device_name}
                data_template:
                  message: Switch turned off because power exceeded ${max_power}W
    frequency:
      name: "Frequency"
      accuracy_decimals: 2
    update_interval: 5s

  - platform: total_daily_energy
    name: "Daily Energy Consumed"
    power_id: power
    filters:
        - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:clock-alert

button:
  - platform: restart
    name: "Restart"

uart:
  id: uart_bus
  tx_pin: GPIO6
  rx_pin: GPIO7
  baud_rate: 9600
  stop_bits: 1