substitutions:
  device_name: heater

esphome:
  name: heater
  friendly_name: Heater

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    advanced:
      ignore_efuse_mac_crc: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "$(device_name) Fallback Hotspot"
    password: !secret wifi_password

logger:

api:
  encryption:
    key: XvJ2I0HQiCVBI2SQGoq/3VNgWcdIZ1h88lgBaTVxKQU=

ota:
  platform: esphome
  password: fe68f08fb30fe4d8dc14604f3eec1a3e

time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO05

# light:
#   - platform: status_led
#     name: "Status LED"
#     pin:
#       number: GPIO00
#       inverted: true
status_led:
  pin:
    number: 0
    inverted: true

switch:
  - platform: output
    id: "relay"
    name: "Power"
    output: "relay_output"

binary_sensor:
  - platform: gpio
    name: "Main Switch"
    pin: GPIO10
    on_state: 
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "Button"
    pin:
      number: GPIO01
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 5ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Device Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
      
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db

  - platform: bl0942
    uart_id: uart_bus
    voltage:
      name: 'Voltage'
    current:
      name: 'Current'
    power:
      name: 'Power'
    frequency:
      name: "Frequency"
      accuracy_decimals: 2
    update_interval: 5s

uart:
  id: uart_bus
  tx_pin: GPIO6
  rx_pin: GPIO7
  baud_rate: 9600
  stop_bits: 1