substitutions:
  name: kauf-bulb-df30fa
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: pK6S/fF0mJMYl3HV7hmawbWdFrQJq8ApPdsAfYO1RqQ=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
