substitutions:
  device_name: "Closet"

esphome:
  name: closet
  friendly_name: Closet
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Fallback Hotspot"
    password: !secret fallback_password

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

output:
  - platform: gpio
    id: "relay_output"
    pin: 7

light:
  - platform: binary
    name: "Light"
    output: relay_output
    id: lightid
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    name: "Wall Switch"
    pin: 10
    on_state:
      then:
        - light.toggle: "lightid"

    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "Button"
    pin:
      number: 1
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - light.toggle: "lightid"   
    filters:
      - delayed_on_off: 5ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Board Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    mac_address:
        name: ESP Mac Wifi Address  

status_led:
  pin:
    number: 0
    inverted: true

captive_portal:
    