substitutions:
  name: ny1-p-kaufb-01
  friendly_name: KAUFB-01
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: KqWfOxGbvpSj6lvEWTgL87NnZNUKk6BtxjBuxH1D1QY=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
