substitutions:
  name: ny1-p-kaufb-02
  friendly_name: KAUFB-02
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: ypjI/iXUaBagq7FytYXG8yYDsue1C96zl0Ojo+OVU4o=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
