substitutions:
  name: ny1-p-bed-01
  friendly_name: NY1-P-BED-01

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret fallback_password

captive_portal:


binary_sensor:
  - platform: template
    name: "Occupancy"
    id: tbr_o
    lambda: return id(tristans_bed_sensor).state < id(trigger_level).state;

sensor:
  - platform: adc
    pin: GPIO34
    attenuation: 12db
    name: "Sensor"
    id: "tristans_bed_sensor"
    icon: mdi:bed
    update_interval: 0.25s
    filters:
      - sliding_window_moving_average:
          window_size: 7
          send_every: 1
      - or:
          - throttle: 180s
          - delta: 0.02

number:
  - platform: template
    name: "Trigger Level"
    id: trigger_level
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 3.5
    step: 0.01
    icon: mdi:arrow-collapse-down
    unit_of_measurement: V