substitutions:
  name: ny1-p-aircon-01 # Do not use underscores, which are not fully compatible with mDNS
  friendly_name: NY1-P-AIRCON-01
  remote_temp_sensor: sensor.tbr_temp
  outside_temp_sensor: sensor.sample_room_temp


packages:
  device_base: !include Base_Confs/MitsubishiCN105.yaml