substitutions:
  name: "ny1-p-kaufsw-01"
  hass_entity_single_press_toggle: "light.kaufsw_lx_group"
  hass_entity_double_press_toggle: "light.rgbw2_01"
packages:
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs-4m.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: NY1-P-KAUFSW-01
api:
  encryption:
    key: !secret api_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
