####################################################
#                                                  #
#             ESP Core Information                 #
#                                                  #
####################################################
esphome:
  name: ny1-p-aircon-01
  friendly_name: NY1-P-AIRCON-01

# For ESP32 Devices
esp32:
 board: esp32dev
 framework:
   type: esp-idf   

uart:
 id: HP_UART
 baud_rate: 2400
 tx_pin: GPIO17
 rx_pin: GPIO16

ota:
  platform: esphome # Required for ESPhome 2024.6.0 and greater
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
        - lambda: 'id(hp).set_remote_temperature(temperature);'
    - service: use_internal_temperature
      then:
        - lambda: 'id(hp).set_remote_temperature(0);'  

# Default logging level
logger:
  baud_rate: 0
  level: INFO
  logs:
    EVT_SETS : INFO
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : INFO
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : INFO
    READ : WARN
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

####################################################
#                                                  #
#              Climate Configuration               #
#                                                  #
####################################################

# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: none
    update_interval: 1300ms 
    icon: mdi:heat-pump
    visual:
      min_temperature: 17
      max_temperature: 31
      temperature_step:
        target_temperature: 1.0
        current_temperature: 1.0
    outside_air_temperature_sensor:
      name: Outside Air Temperature
    vertical_vane_select:
      name: Vertical Vane
    remote_temperature_timeout: 30min
    debounce_delay : 500ms

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

####################################################
#                                                  #
#                     Sensors                      #
#                                                  #
####################################################

text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
    hide_timestamp: true

  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    mac_address:
      name: MAC  

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s

  # External Temp Sensor.
  - platform: homeassistant
    id: current_temp
    entity_id: ${remote_temp_sensor}
    internal: true
    on_value:
      then:
        - lambda: |-
            id(hp).set_remote_temperature(x);
    filters:
      - heartbeat: 45s
  - platform: homeassistant
    id: outside_temp
    name: Outside Temp
    entity_id: ${outside_temp_sensor}
    internal: false

####################################################
#                                                  #
#           Controls and Config Options            #
#                                                  #
####################################################

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart"

light:
  - platform: status_led
    name: "Blue LED"
    pin: GPIO02