homeassistant: true
advanced:
  network_key:
    - 56
    - 38
    - 132
    - 250
    - 74
    - 48
    - 219
    - 190
    - 174
    - 203
    - 14
    - 67
    - 13
    - 74
    - 94
    - 108
  pan_id: 13784
  ext_pan_id:
    - 15
    - 86
    - 136
    - 211
    - 74
    - 32
    - 20
    - 123
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: mooph2fiethaeb8Loorei5sho8vahtae3vuibai4nee1jaeZ1ooch9ath3nizu9p
frontend:
  port: 8099
device_options:
  legacy: false
permit_join: true
devices:
  '0xb4e3f9fffe7569c4':
    friendly_name: LRBTTN
  '0x00158d000926fd82':
    friendly_name: butt
